<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6v1KKyL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6v1KKyL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6v1KKyL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6v1KKyL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6v1KKyL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6v1KKyL',
    'container.build_id' => 'fb8e22a3',
    'container.build_time' => 1583666224,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6v1KKyL');
