<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT1UAXkE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT1UAXkE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT1UAXkE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT1UAXkE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT1UAXkE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T1UAXkE',
    'container.build_id' => '7a3654fa',
    'container.build_time' => 1590600831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT1UAXkE');
