<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container73LRb0I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container73LRb0I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container73LRb0I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container73LRb0I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container73LRb0I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '73LRb0I',
    'container.build_id' => '94120c40',
    'container.build_time' => 1586036627,
], __DIR__.\DIRECTORY_SEPARATOR.'Container73LRb0I');
