#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

pageNotFound:
    path:  /{path}
    defaults:
      {
        _controller: App\Controller\Api\PageNotFoundController::pageNotFoundAction,
        path: ''
      }
    requirements:
        path: .*